name: fast-controllers-npm

on:
  push:
    branches: [ "main" ]

jobs:
  test-publish:

    runs-on: ubuntu-latest

    steps:

    - name: Checking out Project
      uses: actions/checkout@v6

    - name: Use Setup Node.js [24.x]
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Installing Dependencies
      run: npm ci

    - name: Running Tests
      run: npm test

    - name: Compiling TypeScript
      run: rm -rf build && npx tsc

    - name: Copy Files
      run: cp package.json ./build/

    - name: Publishing Package
      working-directory: ./build
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
